/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fib.h"

int *
fib_1_svc(f *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    //printf("\nEntered server fn");
    int n = argp->n;
    int f0 = 0,f1 = 1;

    for(int i=0;i<n;i++)
    {

        printf("\n%d",f0);
        int sum = f0+f1;
        f0 = f1;
        f1 = sum;
        //printf("\ni = %d",i);
    }

    result = f0+f1;
    getchar();
	return &result;
}
