/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fib.h"

bool_t
xdr_f (XDR *xdrs, f *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	return TRUE;
}
