/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fib.h"

void
fibonacci_1(char *host)
{
    //printf("\nEntered client fn!");
	CLIENT *clnt;
	int  *result_1;
	f  fib_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, fibonacci, fib_vers, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    printf("\nEnter any no: ");
    int n=0;
    scanf("%d",&n);
    fib_1_arg.n=n;
    //printf("\nFirst %d nos are: \n",fib_1_arg.n);


    result_1 = fib_1(&fib_1_arg, clnt);
    if (result_1 == (int *) NULL) {
        clnt_perror (clnt, "call failed");
    }



#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	//printf("\nEntered main!");
	fibonacci_1 (host);
exit (0);
}
